CREATE DATABASE DBMONITORAMENTO;
USE DBMONITORAMENTO;

CREATE TABLE RASP_EQUIPAMENTO (
	EQP_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    EQP_DESCRICAO VARCHAR(100) NOT NULL,
    EQP_MODELO VARCHAR(100),
    EQP_CLIENTE INTEGER,
    EQP_IP VARCHAR(20),
    EQP_MAC VARCHAR(100)
);

CREATE TABLE RASP_MONITORAMENTO (
	MON_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MON_COD_RASP INTEGER NOT NULL,
    MON_DATA_INFO TIMESTAMP NOT NULL,
    MON_INFO_CPU_DISP VARCHAR(100),
    MON_INFO_CPU_UTILIZADA VARCHAR(100),
    MON_INFO_RAM_DISP VARCHAR(100),
    MON_INFO_RAM_UTILIZADA VARCHAR(100),
    MON_INFO_DISCO_DISP VARCHAR(100),
    MON_INFO_DISCO_UTILIZADO VARCHAR(100),
    MON_INFO_TEMPERATURA VARCHAR(15),
    MON_INFO_QNTD_PROCESSOS VARCHAR(15),
    MON_INFO_CON_REDE BOOLEAN
);

ALTER TABLE RASP_MONITORAMENTO ADD CONSTRAINT MON_COD_RASP_REF_COD_RASP FOREIGN KEY(MON_COD_RASP) REFERENCES RASP_EQUIPAMENTO(EQP_ID);

INSERT INTO RASP_EQUIPAMENTO VALUES(1, 'Rasp 1', 'fdsfds', 1, 'ffds', 'fdfds');

